// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.20.3
// source: proto/user_feed_service.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetUserAdsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int32                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserAdsRequest) Reset() {
	*x = GetUserAdsRequest{}
	mi := &file_proto_user_feed_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserAdsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserAdsRequest) ProtoMessage() {}

func (x *GetUserAdsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_feed_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserAdsRequest.ProtoReflect.Descriptor instead.
func (*GetUserAdsRequest) Descriptor() ([]byte, []int) {
	return file_proto_user_feed_service_proto_rawDescGZIP(), []int{0}
}

func (x *GetUserAdsRequest) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type GetUserAdsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ads           []*Ad                  `protobuf:"bytes,1,rep,name=ads,proto3" json:"ads,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserAdsResponse) Reset() {
	*x = GetUserAdsResponse{}
	mi := &file_proto_user_feed_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserAdsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserAdsResponse) ProtoMessage() {}

func (x *GetUserAdsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_feed_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserAdsResponse.ProtoReflect.Descriptor instead.
func (*GetUserAdsResponse) Descriptor() ([]byte, []int) {
	return file_proto_user_feed_service_proto_rawDescGZIP(), []int{1}
}

func (x *GetUserAdsResponse) GetAds() []*Ad {
	if x != nil {
		return x.Ads
	}
	return nil
}

type Ad struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StoreName     string                 `protobuf:"bytes,1,opt,name=store_name,json=storeName,proto3" json:"store_name,omitempty"`
	StoreAddress  string                 `protobuf:"bytes,2,opt,name=store_address,json=storeAddress,proto3" json:"store_address,omitempty"`
	AdItems       []*AdItemData          `protobuf:"bytes,3,rep,name=ad_items,json=adItems,proto3" json:"ad_items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ad) Reset() {
	*x = Ad{}
	mi := &file_proto_user_feed_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ad) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ad) ProtoMessage() {}

func (x *Ad) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_feed_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ad.ProtoReflect.Descriptor instead.
func (*Ad) Descriptor() ([]byte, []int) {
	return file_proto_user_feed_service_proto_rawDescGZIP(), []int{2}
}

func (x *Ad) GetStoreName() string {
	if x != nil {
		return x.StoreName
	}
	return ""
}

func (x *Ad) GetStoreAddress() string {
	if x != nil {
		return x.StoreAddress
	}
	return ""
}

func (x *Ad) GetAdItems() []*AdItemData {
	if x != nil {
		return x.AdItems
	}
	return nil
}

type AdItemData struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Ingredient     string                 `protobuf:"bytes,1,opt,name=ingredient,proto3" json:"ingredient,omitempty"`
	Name           string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Price          *float32               `protobuf:"fixed32,3,opt,name=price,proto3,oneof" json:"price,omitempty"`
	Sale           *string                `protobuf:"bytes,4,opt,name=sale,proto3,oneof" json:"sale,omitempty"`
	IngredientType string                 `protobuf:"bytes,5,opt,name=ingredient_type,json=ingredientType,proto3" json:"ingredient_type,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AdItemData) Reset() {
	*x = AdItemData{}
	mi := &file_proto_user_feed_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdItemData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdItemData) ProtoMessage() {}

func (x *AdItemData) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_feed_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdItemData.ProtoReflect.Descriptor instead.
func (*AdItemData) Descriptor() ([]byte, []int) {
	return file_proto_user_feed_service_proto_rawDescGZIP(), []int{3}
}

func (x *AdItemData) GetIngredient() string {
	if x != nil {
		return x.Ingredient
	}
	return ""
}

func (x *AdItemData) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AdItemData) GetPrice() float32 {
	if x != nil && x.Price != nil {
		return *x.Price
	}
	return 0
}

func (x *AdItemData) GetSale() string {
	if x != nil && x.Sale != nil {
		return *x.Sale
	}
	return ""
}

func (x *AdItemData) GetIngredientType() string {
	if x != nil {
		return x.IngredientType
	}
	return ""
}

var File_proto_user_feed_service_proto protoreflect.FileDescriptor

const file_proto_user_feed_service_proto_rawDesc = "" +
	"\n" +
	"\x1dproto/user_feed_service.proto\x12\x02pb\",\n" +
	"\x11GetUserAdsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x05R\x06userId\".\n" +
	"\x12GetUserAdsResponse\x12\x18\n" +
	"\x03ads\x18\x01 \x03(\v2\x06.pb.AdR\x03ads\"s\n" +
	"\x02Ad\x12\x1d\n" +
	"\n" +
	"store_name\x18\x01 \x01(\tR\tstoreName\x12#\n" +
	"\rstore_address\x18\x02 \x01(\tR\fstoreAddress\x12)\n" +
	"\bad_items\x18\x03 \x03(\v2\x0e.pb.AdItemDataR\aadItems\"\xb0\x01\n" +
	"\n" +
	"AdItemData\x12\x1e\n" +
	"\n" +
	"ingredient\x18\x01 \x01(\tR\n" +
	"ingredient\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x19\n" +
	"\x05price\x18\x03 \x01(\x02H\x00R\x05price\x88\x01\x01\x12\x17\n" +
	"\x04sale\x18\x04 \x01(\tH\x01R\x04sale\x88\x01\x01\x12'\n" +
	"\x0fingredient_type\x18\x05 \x01(\tR\x0eingredientTypeB\b\n" +
	"\x06_priceB\a\n" +
	"\x05_sale2N\n" +
	"\x0fUserFeedService\x12;\n" +
	"\n" +
	"GetUserAds\x12\x15.pb.GetUserAdsRequest\x1a\x16.pb.GetUserAdsResponseB\x06Z\x04./pbb\x06proto3"

var (
	file_proto_user_feed_service_proto_rawDescOnce sync.Once
	file_proto_user_feed_service_proto_rawDescData []byte
)

func file_proto_user_feed_service_proto_rawDescGZIP() []byte {
	file_proto_user_feed_service_proto_rawDescOnce.Do(func() {
		file_proto_user_feed_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_user_feed_service_proto_rawDesc), len(file_proto_user_feed_service_proto_rawDesc)))
	})
	return file_proto_user_feed_service_proto_rawDescData
}

var file_proto_user_feed_service_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_user_feed_service_proto_goTypes = []any{
	(*GetUserAdsRequest)(nil),  // 0: pb.GetUserAdsRequest
	(*GetUserAdsResponse)(nil), // 1: pb.GetUserAdsResponse
	(*Ad)(nil),                 // 2: pb.Ad
	(*AdItemData)(nil),         // 3: pb.AdItemData
}
var file_proto_user_feed_service_proto_depIdxs = []int32{
	2, // 0: pb.GetUserAdsResponse.ads:type_name -> pb.Ad
	3, // 1: pb.Ad.ad_items:type_name -> pb.AdItemData
	0, // 2: pb.UserFeedService.GetUserAds:input_type -> pb.GetUserAdsRequest
	1, // 3: pb.UserFeedService.GetUserAds:output_type -> pb.GetUserAdsResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_user_feed_service_proto_init() }
func file_proto_user_feed_service_proto_init() {
	if File_proto_user_feed_service_proto != nil {
		return
	}
	file_proto_user_feed_service_proto_msgTypes[3].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_user_feed_service_proto_rawDesc), len(file_proto_user_feed_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_user_feed_service_proto_goTypes,
		DependencyIndexes: file_proto_user_feed_service_proto_depIdxs,
		MessageInfos:      file_proto_user_feed_service_proto_msgTypes,
	}.Build()
	File_proto_user_feed_service_proto = out.File
	file_proto_user_feed_service_proto_goTypes = nil
	file_proto_user_feed_service_proto_depIdxs = nil
}
