// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.20.3
// source: proto/user_feed_service.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	UserFeedService_GetUserAds_FullMethodName = "/pb.UserFeedService/GetUserAds"
)

// UserFeedServiceClient is the client API for UserFeedService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UserFeedServiceClient interface {
	GetUserAds(ctx context.Context, in *GetUserAdsRequest, opts ...grpc.CallOption) (*GetUserAdsResponse, error)
}

type userFeedServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewUserFeedServiceClient(cc grpc.ClientConnInterface) UserFeedServiceClient {
	return &userFeedServiceClient{cc}
}

func (c *userFeedServiceClient) GetUserAds(ctx context.Context, in *GetUserAdsRequest, opts ...grpc.CallOption) (*GetUserAdsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserAdsResponse)
	err := c.cc.Invoke(ctx, UserFeedService_GetUserAds_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserFeedServiceServer is the server API for UserFeedService service.
// All implementations must embed UnimplementedUserFeedServiceServer
// for forward compatibility.
type UserFeedServiceServer interface {
	GetUserAds(context.Context, *GetUserAdsRequest) (*GetUserAdsResponse, error)
	mustEmbedUnimplementedUserFeedServiceServer()
}

// UnimplementedUserFeedServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedUserFeedServiceServer struct{}

func (UnimplementedUserFeedServiceServer) GetUserAds(context.Context, *GetUserAdsRequest) (*GetUserAdsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserAds not implemented")
}
func (UnimplementedUserFeedServiceServer) mustEmbedUnimplementedUserFeedServiceServer() {}
func (UnimplementedUserFeedServiceServer) testEmbeddedByValue()                         {}

// UnsafeUserFeedServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UserFeedServiceServer will
// result in compilation errors.
type UnsafeUserFeedServiceServer interface {
	mustEmbedUnimplementedUserFeedServiceServer()
}

func RegisterUserFeedServiceServer(s grpc.ServiceRegistrar, srv UserFeedServiceServer) {
	// If the following call pancis, it indicates UnimplementedUserFeedServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&UserFeedService_ServiceDesc, srv)
}

func _UserFeedService_GetUserAds_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserAdsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserFeedServiceServer).GetUserAds(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserFeedService_GetUserAds_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserFeedServiceServer).GetUserAds(ctx, req.(*GetUserAdsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// UserFeedService_ServiceDesc is the grpc.ServiceDesc for UserFeedService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UserFeedService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.UserFeedService",
	HandlerType: (*UserFeedServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetUserAds",
			Handler:    _UserFeedService_GetUserAds_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/user_feed_service.proto",
}
